---
- name: Deploy AAP Instance Group
  hosts: all
  become: true
  gather_facts: true
  vars:
    controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    controller_hostname: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    controller_validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') }}"

    controller_api: "{{ controller_hostname }}/api/controller/v2"
    bundle_dir: "/tmp/{{ inventory_hostname }}_bundle"
    bundle_tar: "{{ bundle_dir }}.tar.gz"

  tasks:
    - name: Create Instance Group
      ansible.controller.instance_group:
        name: "{{ instance_group_name }}"
        state: present
        # Optional: set up how many tasks are allowed to run
        max_concurrent_jobs: 20
        max_forks: 200
        # Policy for automatic addtion of instances (0 = manual)
        policy_instance_percentage: 0
        policy_instance_minimum: 0
      delegate_to: localhost
      register: ig_result

    - name: Show result of Instance Group creation
      ansible.builtin.debug:
        var: ig_result

    - name: Create Instance
      ansible.controller.instance:
        hostname: "{{ inventory_hostname }}"
        node_type: "execution"
        listener_port: 27199
        peers_from_control_nodes: true
        node_state: "installed"
        validate_certs: true
        enabled: true
      delegate_to: localhost
      register: instance_result

    - name: Show result of Instance creation
      ansible.builtin.debug:
        var: instance_result

    - name: Add Instance to Instance Group
      ansible.controller.instance_group:
        name: "{{ instance_group_name }}"
        instances:
          - "{{ inventory_hostname }}"
        state: present
      delegate_to: localhost

    - name: Show result of Instance addition to Instance Group
      ansible.builtin.debug:
        msg: "Instance {{ inventory_hostname }} created in {{ instance_group_name }}"

    - name: Ensure subscription and repo are active
      community.general.rhsm_repository:
        name: ansible-automation-platform-2.6-for-rhel-9-x86_64-rpms
        state: enabled

    - name: Upgrade all packages to the latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install ansible-core
      ansible.builtin.dnf:
        name: ansible-core
        state: present

    - name: Ensure the Python firewalld library is present
      ansible.builtin.dnf:
        name: python3-firewall
        state: present

    - name: Get Instance ID using lookup
      set_fact:
        instance_id: "{{ lookup('ansible.controller.controller_api', 'instances', query_params={'hostname': inventory_hostname})['id'] }}"

    - name: Download Instance Install Bundle
      ansible.builtin.uri:
        url: "{{ controller_api }}/instances/{{ instance_id }}/install_bundle/"
        url_username: "{{ controller_username }}"
        url_password: "{{ controller_password }}"
        validate_certs: "{{ controller_validate_certs }}"
        method: GET
        force_basic_auth: yes
        dest: "{{ bundle_tar }}"
        status_code: 200
      register: bundle_download

    - name: Open Receptor port in firewalld
      ansible.posix.firewalld:
        port: 27199/tcp
        permanent: yes
        state: enabled
        immediate: yes

    - name: Install the mesh using the bundle      
      block:
        - name: Create extraction directory
          ansible.builtin.file:
            path: "{{ bundle_dir }}"
            state: directory
            mode: '0700'

        - name: Unarchive the bundle
          ansible.builtin.unarchive:
            src: "{{ bundle_tar }}"
            dest: "{{ bundle_dir }}"
            remote_src: yes
            extra_opts: ['--strip-components=1']

        - name: Install Ansible requirements from the bundle
          ansible.builtin.command:
            cmd: "ansible-galaxy install -r requirements.yml"
            chdir: "{{ bundle_dir }}"
          register: install_result

        - name: Show result of creation
          ansible.builtin.debug:
            var: install_result

        - name: Install the Mesh Node using the bundle playbook
          ansible.builtin.command:
            cmd: >
              ansible-playbook -i localhost, install_receptor.yml -c local 
              -e "ansible_python_interpreter=/usr/bin/python3"
              -e "ansible_host={{ inventory_hostname }}"
              -e "receptor_host_identifier={{ inventory_hostname }}"
              -e "routable_hostname={{ inventory_hostname }}"
            chdir: "{{ bundle_dir }}"
            # if this file already exists, this task will not be run
            creates: /etc/receptor/receptor.conf
          register: install_result

        - name: Show result of creation
          ansible.builtin.debug:
            var: install_result

      always:
        - name: Cleanup sensitive bundle files
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          loop:
            - "{{ bundle_tar }}"
            - "{{ bundle_dir }}"

    - name: Verify Receptor Service is running
      ansible.builtin.systemd:
        name: receptor
        state: started
        enabled: yes
